#name: Benches Admin-Panel Build & Deploy
#
#on:
#  push:
#    branches:
#      - admin-panel/development
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Build container
#        run: docker-compose up -d --build
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Deploy
#        uses: appleboy/ssh-action@master
#
#        with:
#          HOST: ${{ secrets.FRONTEND_DEPLOY_HOST }}
#          USERNAME: ${{ secrets.FRONTEND_DEPLOY_USER }}
#          PORT: ${{ secrets.FRONTEND_DEPLOY_PORT }}
#          KEY: ${{ secrets.FRONTEND_DEPLOY_SSH_KEY }}
#          script: cd ${{ secrets.FRONTEND_PWD }} && git pull && docker-compose down && docker-compose up -d
